export default {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  INITIAL: 'INITIAL',
  FETCH_PROMOTED: 'FETCH_PROMOTED',
  FETCH_PROMOTED_SUCCESS: 'FETCH_PROMOTED_SUCCESS',
  FETCH_PROMOTED_ERROR: 'FETCH_PROMOTED_ERROR'
};
