export default {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  INITIAL: 'INITIAL',
  FETCH_PROMOTED: 'FETCH_PROMOTED',
  FETCH_PROMOTED_SUCCESS: 'FETCH_PROMOTED_SUCCESS',
  FETCH_PROMOTED_ERROR: 'FETCH_PROMOTED_ERROR',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  FETCH_TILES: 'FETCH_TILES',
  FETCH_TILES_SUCCESS: 'FETCH_TILES_SUCCESS',
  FETCH_TILES_ERROR: 'FETCH_TILES_ERROR',
  FETCH_CITIES: 'FETCH_CITIES',
  FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
  FETCH_CITIES_ERROR: 'FETCH_CITIES_ERROR'
};
